### ISSUE TITLE
No /cfish command in a 1.20.4 server.

### ISSUE THREAD

**Issue by ChengChinHsia-Pig** [Earthcomputer/clientcommands#599] opened 2024-02-09 00:57 UTC

**Comment by R4z0rX** [comment] 2024-02-09 01:02
Duplicate of https://github.com/Earthcomputer/clientcommands/issues/534, and https://github.com/Earthcomputer/clientcommands/issues/580.
It was patched in 1.20.
https://github.com/Earthcomputer/clientcommands/issues/580#issuecomment-1859216796

**Closed as not planned** 2024-02-09 01:14 UTC
