### ISSUE TITLE
Incompatible with Quilt

### ISSUE THREAD

**Issue by Cccc-owo** [Earthcomputer/clientcommands#396] opened 2022-04-22 12:58 UTC
Just like the title.
```Minecraft 1.18.2 with Quilt Loader 0.16.0-beta.8```
[latest.log](https://github.com/Earthcomputer/clientcommands/files/8541163/latest.log)
Enabled mods:
```
- [x] qsl-1.1.0-beta.4_qfapi-1.0.0-beta.8_fapi-0.51.1_mc-1.18.2.jar
- [x] modmenu-3.1.1.jar
- [x] lazydfu-0.1.2.jar
- [x] clientcommands-2.6.6.jar
```

**Comment by RoootTheFox** [comment] 2022-04-24 06:56
ClientCommands has [no issues running on Quilt using the normal Fabric API](https://github.com/Earthcomputer/clientcommands/files/8549147/fabric-api-no-crash.log) for me [(using quilt's fabric api crashes)](https://github.com/Earthcomputer/clientcommands/files/8549151/quilt-sql-crash.log)
That would mean this issue is probably related to [quilt-standard-libraries](https://github.com/QuiltMC/quilt-standard-libraries) or [quilted-fabric-api](https://github.com/QuiltMC/quilted-fabric-api).
Edit: done a bit of research, quilted-fabric-api is missing the [MixinCreativePlayerInventoryGui](https://github.com/FabricMC/fabric/blob/1.18.2/fabric-item-groups-v0/src/main/java/net/fabricmc/fabric/mixin/item/group/client/MixinCreativePlayerInventoryGui.java) class which ClientCommands tries to access, so this is caused by quilted-fabric-api.
A possible workaround would be replacing quilted fabric api's item-groups-v0 module with the default fabric one.
Edit 2: could not get that to load, gave me dependency errors.

**Comment by RoootTheFox** [comment] 2022-04-24 07:56
Made a quick and dirty fix for loading clientcommands on fabric on [my fork](https://github.com/RoootTheFox/clientcommands) that makes it load by removing access to /citemgroup (which is what breaks it).
A compiled jar can be found [here](https://github.com/RoootTheFox/clientcommands/releases/tag/v2.6.6-quiltfix) if needed

**Comment by triphora** [comment] 2022-05-12 17:57
Yeah, this isn't going to be possible for us to fix on the Quilt side of things.

It's not a matter of a simple class/field not found -- it takes the `fabric_currentPage` field in the transformed jar, makes it accessible via reflection, and sets it to zero when any of its own client-sided item groups are deleted -- which means it isn't really possible for us to do this.

If anyone looking at this wants to PR/implement a fix in CC, it's a matter of checking whether `quilt$currentPage` is there instead of `fabric_currentPage`. Or both, preferably.

**Comment by Earthcomputer** [comment] 2022-05-12 18:44
Agreed - this is something to be fixed in clientcommands, not QSL. It's just not been a higher priority than working on multiconnect. Echoing waffle's comment above about a PR, and thanks for pointer.

**Closed as completed** 2022-05-28 21:02 UTC
