### ISSUE TITLE
player.rightClick in branch_mine crashes the game on 1.15.1

### ISSUE THREAD

**Issue by xaengceilbiths** [Earthcomputer/clientcommands#103] opened 2020-01-22 12:10 UTC
Linux java8 
The following code will freeze the screen without printing anything. 
Meanwhile, commandblock(to get rid of rain) in the spawn chunk keeps running.
I have torches in hand.

Without rightClick code, it runs well.
For 1.14.4, https://github.com/Earthcomputer/clientcommands/blob/1134f4738225a0a999213ff0d9081a8b63dc63a9/docs/example_scripts/branch_mine.js runs ok.

```javascript
var makeTunnel1 = function(x, y, z, dx, dz) {
    centerPlayer();

    // walk to next spot
    if (!player.moveTo(x + dx + 0.5, z + dz + 0.5, false))
        throw new Error();
    if (world.getBlockLight(x, y, z) <= 15) {
        if (!player.pick("torch"))
            throw new Error();
        if (!player.rightClick(x, y - 1, z, "up"))
            print("Couldn't place torch");
    }

    return true;
};

var testLoop = function() {
    try {
        var x = Math.floor(player.x);
        var y = Math.floor(player.y);
        var z = Math.floor(player.z);
        var dx = 1, dz = 0;

        for (var i = 0; i < 10; i++) {
            if (makeTunnel1(x, y, z, dx, dz)) {
                x += dx;
                z += dz;
            }
            print("111");
        }
    } finally {
        print("finally");
    }
};
```

**Comment by xaengceilbiths** [comment] 2020-01-28 07:00
Hack fixed.
```diff
ScriptPlayer.java
---    closestPos = MathUtil.getClosestVisiblePoint(world, pos, origin, getPlayer(), dir);
+++    closestPos = new Vec3d((float)x + 0.5, (float)y, (float)z + 0.5);
```

A better hack fix:
```diff
ScriptPlayer.java
---    closestPos = MathUtil.getClosestVisiblePoint(world, pos, origin, getPlayer(), dir);
+++    float dx = side == "west" ? 1.0 : (side == "east" ? 0.0 : 0.5);
+++    float dz = side == "south" ? 1.0 : (side == "north" ? 0.0 : 0.5);
+++    float dy = side == "up" ? 0.0 : (side == "bottom" ? -1.0 : -0.5);
+++    dy = side == null ? 0.0 : dy;
+++    closestPos = new Vec3d((float)x + dx, (float)y + dy, (float)z + dz);
```

**Comment by Earthcomputer** [comment] 2020-01-30 11:42
I cannot reproduce this error. What other mods are you using?
![image](https://user-images.githubusercontent.com/13084089/73447093-f0d51900-4355-11ea-9c4e-0b7a503f7219.png)

**Comment by xaengceilbiths** [comment] 2020-02-19 13:44
I'm now using 1.15.1, fabric-api-0.4.29+build.290-1.15.jar, clientcommands-2.3.7-pre3.jar, no other mods.
Environment: Linux, kernel:4.8.17, openjdk version "1.8.0_192"
The game still freezes.
Maybe try the script on 'super flat world' where torches can always be placed manually? (ensure having torches in hand)

**Comment by xaengceilbiths** [comment] 2020-02-19 14:03
game command line(slightly changed):
/usr/lib/jvm/java-8-openjdk/jre/bin/java -Dminecraft.client.jar=/home/xxx/game/fabric-1.15-test2/versions/1.15.1/1.15.1.jar -Duser.home=/home/xxx/game -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3968m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -Djava.library.path=/home/xxx/game/fabric-1.15-test2/versions/1.15.1/1.15.1-natives -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.2.139 -cp lib/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar:lib/net/fabricmc/sponge-mixin/0.8+build.16/sponge-mixin-0.8+build.16.jar:lib/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar:lib/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar:lib/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar:lib/org/ow2/asm/asm/7.2/asm-7.2.jar:lib/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar:lib/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar:lib/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar:lib/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar:lib/com/google/guava/guava/21.0/guava-21.0.jar:lib/net/fabricmc/intermediary/1.15.1/intermediary-1.15.1.jar:lib/net/fabricmc/fabric-loader/0.7.2+build.175/fabric-loader-0.7.2+build.175.jar:lib/com/mojang/patchy/1.1/patchy-1.1.jar:lib/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:lib/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:lib/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:lib/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:lib/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:lib/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:lib/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:lib/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:lib/commons-io/commons-io/2.5/commons-io-2.5.jar:lib/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:lib/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:lib/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:lib/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:lib/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar:lib/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:lib/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:lib/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:lib/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:lib/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:lib/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:lib/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:lib/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:lib/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:lib/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:lib/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:lib/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:lib/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:lib/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:lib/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:lib/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:lib/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/home/xxx/game/fabric-1.15-test2/versions/1.15.1/1.15.1.jar net.fabricmc.loader.launch.knot.KnotClient --username xxxxx --version HMCL 3.2.139 --gameDir /home/xxx/game/fabric-1.15-test2 --assetsDir /home/xxx/game/fabric-1.15-test2/assets --assetIndex 1.15 --uuid xxxxx --accessToken xxx--userType mojang --versionType HMCL 3.2.139 --width 854 --height 480

**Comment by Earthcomputer** [comment] 2020-03-12 15:56
I believe I have finally managed to reproduce this. The reason I couldn't before is that it only occurs when your x-coordinate is less than your z-coordinate.

**Comment by Earthcomputer** [comment] 2020-03-12 19:11
Will be fixed in pre7 when it comes out

**Closed as completed by Earthcomputer** 2020-03-12 19:11 UTC
Labels: bug
