### ISSUE TITLE
remove cbook

### ISSUE THREAD

**Issue by CraftalotReloaded** [Earthcomputer/clientcommands#17] opened 2019-03-19 22:11 UTC
Remove the darn cbook stuff, you're just breaking servers with this

**Comment by Vonr** [comment] 2019-03-19 22:29
Wasn't his fault. Also wouldn't fix anything. You can still copy and paste
characters manually. It is also fixed on newer versions of Sponge, Spigot,
Paper, Forge, and Bukkit. Meaning that it is fixed on pretty much every
server with a smart owner.

**Comment by Mhowser** [comment] 2019-03-19 22:31
Servers should have updated to prevent this from happening. But they dont, so we'll continue to use cbook

**Comment by CraftalotReloaded** [comment] 2019-03-19 22:34
Not fully fixed on forge yet

**Comment by Vonr** [comment] 2019-03-19 23:15
Are you sure you're on the latest/bery much newer versions?

**Comment by CraftalotReloaded** [comment] 2019-03-20 00:00
Everything is up to date

**Comment by KaptainWutax** [comment] 2019-03-20 11:02
Cbook does not corrupt chunks, it just prevents them for being written to disk. In fact, no save = less chance of corruption.

**Comment by CraftalotReloaded** [comment] 2019-03-20 17:35
It will try to save and in some cases it will partially save and corrupt the chunk

**Comment by Earthcomputer** [comment] 2019-03-20 17:47
Whatever issues you're having with this they have nothing to do with clientcommands. If you think the chunk corruption is being caused by Forge, please take the issue up with that. And no, I won't be removing this feature.

**Closed by Earthcomputer** 2019-03-20 17:47 UTC

**Comment by CraftalotReloaded** [comment] 2019-03-20 17:52
Forge blamed the books

**Comment by CraftalotReloaded** [comment] 2019-03-20 17:52
The books you made even easyer to create

**Comment by Vonr** [comment] 2019-03-20 23:38
Forge. Has. Already. Patched. It. On. The. Latest. Version. By. Allowing. Oversized. Chunks. To. Save.

**Comment by Earthcomputer** [comment] 2019-03-21 11:36
In any case, if you think it's the books' fault then blame vanilla. My mod didn't add books.
