### ISSUE TITLE
Problems related to Optifine Shaders

### ISSUE THREAD

**Issue by MrBored** [Earthcomputer/clientcommands#294] opened 2021-07-12 06:06 UTC
After installing this mod, opening Optifine shaders will cause serious errors.

This is BSL_v8.0.01 shaderpackage, looks no problem, But if you into the water....
![BSL Shaderpack](https://user-images.githubusercontent.com/52899122/125237240-f343ec80-e317-11eb-8484-ffeedf392d10.png)
It will become like this !
![BSL_v8 0 01  In Water](https://user-images.githubusercontent.com/52899122/125237247-f7700a00-e317-11eb-9ad7-8421733382df.png)
If you change the shadowpackage ex.Sildurs Vibrant Shaders v1.29 Medium, there will be more problems.
![Sildurs Vibrant Shaders v1 29 Medium](https://user-images.githubusercontent.com/52899122/125237256-fa6afa80-e317-11eb-8d05-a54dbbd983cb.png)

I only have to install this mod, Optifine and OptiFabric.

Optifine version: OptiFine HD U G9 pre26
OptiFabric version: OptiFabric-v1.11.17
Client Commands version: 2.5.1

By the way, My Minecrat fabric version is 1.17.

Sorry, my English is not very good, English is all translated by Google, there may be grammatical errors.
Hope it can be resolved, thank you ^^

**Comment by Earthcomputer** [comment] 2021-07-12 09:06
Duplicate of #269

**Closed as completed by Earthcomputer** 2021-07-12 09:06 UTC
