### ISSUE TITLE
[FUTURE] /cfindblockall [args...]

### ISSUE THREAD

**Issue by zyxkad** [Earthcomputer/clientcommands#345] opened 2021-12-17 23:50 UTC
**Command: `cfindblockall`**
**Arguments: *As same as `cfindblock`* **
**Do what: Find all matched block, not just the nearest one.**

**Comment by m-sarabi** [comment] 2021-12-18 18:22
duplicate of #78 I think

**Closed as completed** 2023-01-08 23:02 UTC
Labels: duplicate
