### ISSUE TITLE
Can the types of enhanced book trading with villagers controlled by this mod？

### ISSUE THREAD

**Issue by crosspedestrian** [Earthcomputer/clientcommands#184] opened 2021-02-16 02:35 UTC
Well, when building a villagers exchange, the enhanced book I want is hard to show up, especially sharpness V lol. 
So can the mod control what items show up when a villager get his work next time?
Thanks.

**Comment by Earthcomputer** [comment] 2021-02-16 08:33
Duplicate of #114

**Closed as completed by Earthcomputer** 2021-02-16 08:33 UTC
