### ISSUE TITLE
Game Crash when /citemgroup remove 1

### ISSUE THREAD

**Issue by Nitwilli** [Earthcomputer/clientcommands#287] opened 2021-06-27 08:12 UTC
I have a problem where i added a Itemgroup successfully but when i tried to remove it (/citemgroup remove 1) my game crashed.
Here is the Log: **https://paste.ee/p/QsLms**
 @**Information:**

Version: 1.17 Fabric
Mods: clientcommands, Inventory HUD+, Inventory Sorting, OK Zoomer, Krypton, Lithium, Mod Menu, Fabric API, Simple Voice Chat

**Comment by Nitwilli** [comment] 2021-06-27 08:13
I was using MultiMC btw

**Comment by barraIhsan** [comment] 2021-06-27 08:14
See #272

**Comment by Earthcomputer** [comment] 2021-07-03 17:37
Duplicate of #272

**Closed as completed by Earthcomputer** 2021-07-03 17:37 UTC
