### ISSUE TITLE
[ISSUE] Mod breaks shaders

### ISSUE THREAD

**Issue by Tnology** [Earthcomputer/clientcommands#316] opened 2021-08-24 03:46 UTC
For some reason this mod completely breaks shaders with OptiFabric + OptiFine. Here's the mod list (including ClientCommands) that the shaders break on:
[1.16.2][Fabric]+RPG-HUD-3.8.1.jar
AdvancedChat-2.1.1.jar
advanced-nbt-tooltip-1.4.0+build.3-1.16.5.jar
betterf3-1.1.2+1.16.2.jar
fabric-api-0.30.0+1.16.jar
fabricmod_VoxelMap-1.10.14_for_1.16.4.jar
Hwyla-fabric-1.16.2-1.9.23-79.jar
modmenu-1.16.6.jar
mousewheelie-1.6.4+mc1.16.4.jar
optifabric-1.9.2.jar
OptiFine_1.16.5_HD_U_G6.jar
preciseblockplacing-1.0.6+1.16.5.jar
replaymod-1.16.4-2.6.0.jar
shulkerboxtooltip-2.3.5+1.16.5.jar
clientcommands-2.4.11.jar

When closing Minecraft, removing the mod from the mods folder, and restarting Minecraft, the shaders work fine. This mod breaks both SEUS Renewed shaders and Continuum shaders.

**Comment by barraIhsan** [comment] 2021-08-24 03:47
Duplicate of #269

**Closed as completed** 2021-08-24 09:02 UTC
