### ISSUE TITLE
not an issue but quick question

### ISSUE THREAD

**Issue by arceuss** [Earthcomputer/clientcommands#136] opened 2020-08-11 02:23 UTC
is it possible to make something that cracks the world seed

**Comment by Mhowser** [comment] 2020-08-11 04:42
There is mod that does this already, its made by Kaptain Wutax, search his
name on github. You'll find it.

**Comment by Earthcomputer** [comment] 2020-08-11 07:31
Duplicate of #85

**Closed as completed by Earthcomputer** 2020-08-11 07:31 UTC
