### ISSUE TITLE
Command crashes with Oh My Minecraft Client

### ISSUE THREAD

**Issue by Notoriousi** [Earthcomputer/clientcommands#456] opened 2022-10-28 17:20 UTC
Not sure where to leave it so ill leave it here. Tested the mod without any other mods installed and it works perfectly fine. however half of the commands seem to be incompatible with (some of) my mods. Getting crashing using /clook and /cfindblock to name 2 Crash log below:

**Update:** its incompatible with ohmyminecraft client. after seeing another issue report on this case i tried all my mods minus ommc and it works perfectly. Duplicate of: #449 (though /clook, /cfindblock are also not working, not just /cglow)

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2022-10-28 19:18:40
Description: keyPressed event handler

java.lang.AbstractMethodError: Receiver class net.minecraft.class_637 does not define or inherit an implementation of the resolved method 'net.minecraft.class_243 getPosition()' of interface net.fabricmc.fabric.api.client.command.v2.FabricClientCommandSource.
	at net.earthcomputer.clientcommands.command.FindBlockCommand.findBlockCandidatesInSquareArea(FindBlockCommand.java:73)
	at net.earthcomputer.clientcommands.command.FindBlockCommand.findBlock(FindBlockCommand.java:48)
	at net.earthcomputer.clientcommands.command.FindBlockCommand.lambda$register$0(FindBlockCommand.java:32)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:142)
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.executeCommand(ClientCommandInternals.java:89)
	at net.minecraft.class_746.handler$dle001$onSendCommand(class_746.java:4908)
	at net.minecraft.class_746.method_44098(class_746.java)
	at net.minecraft.class_408.method_44056(class_408.java:517)
	at net.minecraft.class_408.method_25404(class_408.java:213)
	at net.minecraft.class_309.method_1454(class_309.java:374)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.earthcomputer.clientcommands.command.FindBlockCommand.findBlockCandidatesInSquareArea(FindBlockCommand.java:73)
	at net.earthcomputer.clientcommands.command.FindBlockCommand.findBlock(FindBlockCommand.java:48)
	at net.earthcomputer.clientcommands.command.FindBlockCommand.lambda$register$0(FindBlockCommand.java:32)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:142)
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.executeCommand(ClientCommandInternals.java:89)
	at net.minecraft.class_746.handler$dle001$onSendCommand(class_746.java:4908)
	at net.minecraft.class_746.method_44098(class_746.java)
	at net.minecraft.class_408.method_44056(class_408.java:517)
	at net.minecraft.class_408.method_25404(class_408.java:213)
	at net.minecraft.class_309.method_1454(class_309.java:374)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

-- Affected level --
Details:
	All players: 1 total; [class_746['Notoriousi'/3779488, l='ClientLevel', x=773.00, y=118.58, z=-254.84]]
	Chunk stats: 4096, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,77,16), Section: (at 0,13,0 in 0,4,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 574487033 game time, 605227345 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks 16 July.zip, continuity/default, continuity/glass_pane_culling_fix, God Minecraft.zip, FreshAnimations_v1.7_S7.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.4.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 8985356872 bytes (8569 MiB) / 17179869184 bytes (16384 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce GTX 1080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b06
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2647
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 53501.30
	Virtual memory used (MB): 31776.10
	Swap memory total (MB): 20992.00
	Swap memory used (MB): 514.15
	JVM Flags: 9 total; -XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms16384m -Xmx16384m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
		bedrockminer: Bedrock Miner 1.0.0
		betterf3: BetterF3 4.0.0
			cloth-config: Cloth Config v8 8.2.88
				cloth-basic-math: cloth-basic-math 0.6.1
		capes: Capes 1.4.5+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		carpet: Carpet Mod 1.4.84
		carpet-extra: Carpet Extra 1.4.83
		carpet-fixes: Carpet Fixes 1.19-1.12.2
			conditional-mixin: conditional mixin 0.3.1
		carpet-shadow: Carpet Shadow 1.9.6-MC1.19+
		carpet-tis-addition: Carpet TIS Addition 1.41.1
			org_yaml_snakeyaml: snakeyaml 1.30
		cem: Custom Entity Models 0.7.1_S6_1.19
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
		clientcommands: Client Commands 2.7.4
			clientarguments: clientarguments 1.4.1
			multiconnect-api: MultiConnect API 1.5.10
		continuity: Continuity 2.0.1+1.19
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entity_texture_features: Entity Texture Features 4.1.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		essential-client: Essential Client 1.3.1
			com_github_senseiwells_arucas: Arucas 017c7b2aef
		fabric-api: Fabric API 0.64.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.12+c0ae659d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.14+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.9
		fabrishot: Fabrishot 1.9.1
		geodesy: Geodesy 2.1
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		itemscroller: Item Scroller craftfix-1.2.6
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.12.5
		litematica_printer: Litematica Printer 6.8.0
		lithium: Lithium 0.10.0
		lod: Distant Horizons 1.6.9a
		magiclib: MagicLib 0.5.37
			magiclib-1_19_2: MagicLib for 1.19.2 0.5.37
		malilib: MaLiLib 0.13.0
		masa_gadget_mod: Masa Gadget 3.0.0-beta+bc54082
			masa_gadget_mod-1_19_2: Masa Gadget for 1.19.2 3.0.0-beta+bc54082
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.0.6
		moreculling: More Culling 1.19.1-0.10.0
		nochatreports: No Chat Reports 1.19.2-v1.13.10
		ommc: Oh My Minecraft Client 0.5-beta+657858c
			ommc-1_19_2: Oh My Minecraft Client for 1.19.2 0.5-beta+657858c
		pca: Plusls carpet addition mod 0.2.5-beta+2db20d6
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		replaymod: Replay Mod 1.19.1-2.6.8
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.11+mc1.19.2-build.68
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		syncmatica: Syncmatica 0.3.5
		tweakermore: TweakerMore 3.7.1
		tweakeroo: Tweakeroo 0.14.3
		voicechat: Simple Voice Chat 1.19.2-2.3.12
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		xaerominimap: Xaero's Minimap 22.16.0
		xaeroworldmap: Xaero's World Map 1.28.1
		yet-another-config-lib: YetAnotherConfigLib 1.6.0
		zoomify: Zoomify 2.8.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
			dev_isxander_settxi_settxi-core: settxi-core 2.10.3
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.3
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.3
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.3
	Loaded Shaderpack: (off)
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 526.47, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks 16 July.zip, continuity/default, continuity/glass_pane_culling_fix, file/God Minecraft.zip, file/FreshAnimations_v1.7_S7.zip
	Current Language: English (United Kingdom)
	CPU: 24x 12th Gen Intel(R) Core(TM) i9-12900K
```

**Comment by haykam821** [comment] 2022-10-28 17:46
It appears that Oh My Minecraft Client breaks the implementation of Fabric Command API v2. Client Commands uses Fabric API in a correct way:

https://github.com/Earthcomputer/clientcommands/blob/d99df75d4e1ceb64faed0e563c1630ef4a0095c3/src/main/java/net/earthcomputer/clientcommands/command/FindBlockCommand.java#L73

**Comment by Notoriousi** [comment] 2022-10-28 17:50
> It appears that Oh My Minecraft Client breaks the implementation of Fabric Command API v2. Client Commands uses Fabric API in a correct way:
> 
> https://github.com/Earthcomputer/clientcommands/blob/d99df75d4e1ceb64faed0e563c1630ef4a0095c3/src/main/java/net/earthcomputer/clientcommands/command/FindBlockCommand.java#L73

I've also put a issue there. Feel free to close this issue if its on OMMC to fix the implementation

**Comment by haykam821** [comment] 2022-10-28 17:50
Relates to plusls/oh-my-minecraft-client#47, plusls/oh-my-minecraft-client#55, and plusls/oh-my-minecraft-client#61

**Comment by Earthcomputer** [comment] 2023-01-08 23:20
Duplicate of #423

**Closed as completed by Earthcomputer** 2023-01-08 23:20 UTC
