### ISSUE TITLE
/cfindblock Error

### ISSUE THREAD

**Issue by LynnGuo666** [Earthcomputer/clientcommands#502] opened 2023-01-31 05:21 UTC
When I use /cfindblock ,the minecraft will be crashed.
Message:
[13:17:53] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: keyPressed event handler
	at net.minecraft.class_437.method_25412(class_437.java:494) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:370) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:462) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:462) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:315) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1205) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class net.minecraft.class_637 does not define or inherit an implementation of the resolved method 'net.minecraft.class_243 getPosition()' of interface net.fabricmc.fabric.api.client.command.v2.FabricClientCommandSource.
	at net.earthcomputer.clientcommands.command.FindBlockCommand.findBlockCandidatesInSquareArea(FindBlockCommand.java:73) ~[clientcommands-2.7.5.jar:?]
	at net.earthcomputer.clientcommands.command.FindBlockCommand.findBlock(FindBlockCommand.java:48) ~[clientcommands-2.7.5.jar:?]
	at net.earthcomputer.clientcommands.command.FindBlockCommand.lambda$register$0(FindBlockCommand.java:32) ~[clientcommands-2.7.5.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:142) ~[brigadier-1.0.18.jar:?]
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.executeCommand(ClientCommandInternals.java:89) ~[fabric-command-api-v2-2.1.10+93d8cb8290-5d1820f9516c4.jar:?]
	at net.minecraft.class_746.handler$zip001$onSendCommand(class_746.java:3408) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_44098(class_746.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_44056(class_408.java:517) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_25404(class_408.java:213) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1454(class_309.java:374) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:489) ~[client-intermediary.jar:?]
	... 22 more

Log:
[latest.log](https://github.com/Earthcomputer/clientcommands/files/10543051/latest.log)

**Comment by Earthcomputer** [comment] 2023-04-19 20:39
Duplicate of #423

**Closed as completed by Earthcomputer** 2023-04-19 20:39 UTC
Labels: bug
