### ISSUE TITLE
FR: /cnbt

### ISSUE THREAD

**Issue by EvModder** [Earthcomputer/clientcommands#565] opened 2023-08-30 09:31 UTC
`/cNBT` - print handheld item NBT (json) to chat console.
Feature exists in some "hack" mods (such as Wurst), if that's helpful as a reference.

Feel free to close this FR if this is out of scope for what you want in ClientCommands; to me it seemed a natural fit

**Comment by xpple** [comment] 2023-08-30 13:11
Duplicate of #503.

**Closed as not planned by xpple** 2023-08-30 13:11 UTC
Labels: duplicate, enhancement
