### ISSUE TITLE
Execution of the /cfind instruction crashed

### ISSUE THREAD

**Issue by yuyi2439** [Earthcomputer/clientcommands#431] opened 2022-07-07 03:08 UTC
[crash-2022-07-07_11.05.43-client.txt](https://github.com/Earthcomputer/clientcommands/files/9060067/crash-2022-07-07_11.05.43-client.txt)

**Comment by CodeF53** [comment] 2022-07-13 00:07
I have this issue aswell
https://crashy.net/7ssyRxOrCUDuQPVvD6jc

**Comment by Earthcomputer** [comment] 2022-07-13 01:36
Can you both try and find out which mod it's conflicting with. This doesn't happen with just clientcommands (and fabric api)

**Comment by CodeF53** [comment] 2022-07-13 04:10
Will look into it tomorrow

**Comment by yuyi2439** [comment] 2022-07-13 06:06
Clientcommands mod conflicts with oh-my-minecraft-client mod
[oh-my-minecraft-client](https://github.com/plusls/oh-my-minecraft-client)
xaero-map-addition mod depends on it
I need a feature of xaero-map-addition mod

**Comment by Earthcomputer** [comment] 2023-01-08 23:19
Duplicate of #423

**Closed as completed by Earthcomputer** 2023-01-08 23:19 UTC
