### ISSUE TITLE
Option to force /cenchant to use only certain number of bookshelves.

### ISSUE THREAD

**Issue by nayfaan** [Earthcomputer/clientcommands#611] opened 2024-03-25 06:28 UTC
Building upon #586, I would like to see either a config option or extra argument to the /cenchant command where the user can set the number of bookshelves they want. That will then force the command to reroll to only show results using said number of bookshelves. It's not always easy to remove / block booksehlves, especially since I'd imagine a lot of people would be using something like all 32 bookshelves for aesthetics reasons

**Comment by Earthcomputer** [comment] 2024-03-25 13:28
Duplicate of #178

**Closed as completed by Earthcomputer** 2024-03-25 13:28 UTC
