### ISSUE TITLE
Feature Request: Reducing Client-Server Lag/Latancy Slowdowns In Farms With Client Side Ghost Blocks

### ISSUE THREAD

**Issue by Sopitive** [Earthcomputer/clientcommands#195] opened 2021-02-27 06:21 UTC
One issue I have had on a multitude of servers is that my ping is much too high to be able to handle the actual speed and potential of the farm where I am mining. Is it possible to add a command that sets specific ghost blocks in a predefined area such as /csetghost or /csetblock? It would be most useful in situations where either a farm is so big that it causes slowdowns client side resulting in slower block breaking speed or in situations where your ping is really high and you cannot break the next block until the server sends the block information back on that location. Basalt farms, ice farms, cobble/stone farms etc would be examples of this where blocks are quickly replaced in front of the player in this way.

**Comment by Earthcomputer** [comment] 2021-02-27 10:05
Duplicate of #153

**Closed as completed by Earthcomputer** 2021-02-27 10:05 UTC
