### ISSUE TITLE
No cfish

### ISSUE THREAD

**Issue by TherealONE12** [Earthcomputer/clientcommands#580] opened 2023-12-17 15:23 UTC
I cant find the command /cfish in 1.20.4

**Comment by TherealONE12** [comment] 2023-12-17 15:47
And whats /startup?

**Comment by Gaming32** [comment] 2023-12-17 16:28
/cfish doesn't work in 1.20. The command is available if you connect to older servers with ViaFabricPlus.

**Comment by haykam821** [comment] 2023-12-17 16:58
Duplicate of #534 and #577

**Closed as not planned** 2023-12-17 16:58 UTC
