### ISSUE TITLE
[Suggestion] Automatic trade rerolling (/creroll)

### ISSUE THREAD

**Issue by Spritzerland** [Earthcomputer/clientcommands#489] opened 2023-01-08 22:56 UTC
I'm tired of breaking and placing lecterns and other stuff to reroll the trades. Could there by an automatic break/place command, that is done by a command? Here's an example:
/creroll librarian with minecraft:protection 4
This would break the lectern, place it, wait until the villager is enrolled in the job, then check if protection 4 is in the trades.
I don't think that it could be manipulated, but i'm not sure about it

**Comment by Earthcomputer** [comment] 2023-01-08 23:29
I'm going to close this as a duplicate of #114 not because it's an exact duplicate, but because this is actually how trade manipulation would work (with some RNG prediction to make it faster)

**Closed as completed by Earthcomputer** 2023-01-08 23:29 UTC
